### ISSUE TITLE
link with google home @ android failes

### ISSUE THREAD

**Issue by maruether** [openhab/openhab-google-assistant#177]
When I try to add my openhab-cloud to google home and press the "Allow" button, the app try's to link, but no switch is available.
In the output of the openhab cloud i got the following error:

scope option is deprecated and will be removed in EJS 3
ForbiddenError: invalid csrf token
    at csrf (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/csurf/index.js:112:19)
    at /var/www/clients/client1/web9/web/openhab-cloud/app.js:285:9
    at Layer.handle [as handle_request] (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:317:13)
    at /var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:275:10)
    at /var/www/clients/client1/web9/web/openhab-cloud/app.js:279:5
    at Layer.handle [as handle_request] (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:317:13)
    at /var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:335:12)
    at Context.next (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:275:10)
    at Context.actions.pass (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/passport/lib/passport/context/http/actions.js:77:8)
    at SessionStrategy.authenticate (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/passport/lib/passport/strategies/session.js:67:10)
    at attempt (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
    at Passport.authenticate (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
    at Layer.handle [as handle_request] (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:317:13)
    at /var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/clients/client1/web9/web/openhab-cloud/node_modules/express/lib/router/index.js:275:10)

**Comment by michikrug** [comment]
As this seems to be an openhab cloud issue, would you mind raising it at https://github.com/openhab/openhab-cloud ?

**Comment by michikrug** [comment]
A reason I could imagine is an error you made during the setup of the Google Action

https://github.com/openhab/openhab-google-assistant#actions-on-google

**Comment by maruether** [comment]
Thank you, i'm an idiot. I forgot the "oauth2" part in the token-url.

CLOSED
