### ISSUE TITLE
pinNeeded isn't working for me!

### ISSUE THREAD

**Issue by cholawo** [openhab/openhab-google-assistant#182]
@michikrug I was eager to test the new features from your extensive refactoring pull request but I can't get `pinNeeded` to work after I updated my item in openhab.  I don't think I've done anything wrong to break it and as far as I can tell your refactor pull request isn't aware of any issue?
When I attempt to unlock the door, Google reports an error "Sorry I couldn't reach..." instead of asking me for the pin.

Looking through the code I see that `handleExecute` is passing an undefined `execution.challenge` to `handleAuthPin`, and then `handleAuthPin` throws an error `Cannot read property 'pin' of undefined`.

I guess this is because Google isn't even asking me for the pin.   I have tried removing the lock from my google home by removing the `ga="Lock"` tag from the item, saying "sync my devices", then re-adding the tag and syncing again.   Here's the full log including the console.log from handleExecute.

```
openhabGoogleAssistant - handleExecute - commands: [{"devices":[{"customData":{"deviceType":"Lock","itemType":"Switch","pinNeeded":"1234"},"id":"ZWaveNode004SDL1000CHYaleConexisL1_DoorLock"}],"execution":[{"command":"action.devices.commands.LockUnlock","params":{"lock":false}}]}]
openhabGoogleAssistant - action.devices.commands.LockUnlock: {"devices":[{"customData":{"deviceType":"Lock","itemType":"Switch","pinNeeded":"1234"},"id":"ZWaveNode004SDL1000CHYaleConexisL1_DoorLock"}],"params":{"lock":false}}
TypeError: Cannot read property 'pin' of undefined
    at Function.handleAuthPin (/home/openhab-google-assistant/functions/commands/default.js:64:73)
    at devices.map (/home/openhab-google-assistant/functions/commands/default.js:108:36)
    at Array.map (<anonymous>)
    at Function.execute (/home/openhab-google-assistant/functions/commands/default.js:106:30)
    at command.execution.forEach (/home/openhab-google-assistant/functions/openhab.js:212:35)
    at Array.forEach (<anonymous>)
    at commands.forEach (/home/openhab-google-assistant/functions/openhab.js:191:25)
    at Array.forEach (<anonymous>)
    at OpenHAB.handleExecute (/home/openhab-google-assistant/functions/openhab.js:190:14)
    at OpenHAB.onExecute (/home/openhab-google-assistant/functions/openhab.js:131:32)
```
my item definition
```
Switch ZWaveNode004SDL1000CHYaleConexisL1_DoorLock "Front door lock" { channel="zwave:device:aeotec:node4:lock_door", ga="Lock" [ pinNeeded="1234" ]}
```

**Comment by michikrug** [comment]
Thanks for the report. I will have a look.

**Comment by michikrug** [comment]
Fixed with https://github.com/openhab/openhab-google-assistant/pull/175/commits/ce2d866c632f1c1db9ea087d76dd7cd4c2995744

Thanks again for testing :)
