### ISSUE TITLE
Add new items are not listed in Google home 

### ISSUE THREAD

**Issue by Rar9** [openhab/openhab-google-assistant#5]
Once linked,  adding new items like switches, to an existing link are not being recognized.

**Comment by marziman** [comment]
This sth Google didnt support in the SYNC. It also not an issue of this implementation. But I will check if Google has any way to recognize this now. Until then we better keep this issue.

**Comment by skimdankish** [comment]
I am seeing this as well.  A (rather tedious) workaround is to unlink and relink - unfortunately, rooms are not saved like my Wemo and Hue devices.  Seems like SYNC only happens upon linking?

My guess (knowing VERY little about Cloud Functions) is that there would need to be a SYNC trigger within OpenHAB itself...perhaps??

**Comment by swampdogmash** [comment]
This seems to be an issue on things like eWeLink app too. In an Alexa skill there is a "rediscover" type action when you go into the skill and ask to add a new device it goes off and rescans. There seems to be no such function on the Google home version if the integration. Have Google still not implemented a reSYNC action that you can use in the openhab connector?

**Comment by skimdankish** [comment]
Revisiting this, if you say "Hey google, sync lights" it will send the SYNC command to all services/actions currently connected to the account.

**Comment by renegade2k** [comment]
I also see this problem, which i would not relate directly to openhab, as the same problem is there for me linking "smart home" devices. They are also only recognized, while linking. Adding new devices after the account has been linked, they will not show up.
@skimdankish did i get you right: you are able to tell "hey google sync devices" and google will receive all the new linked devices from openhab?

**Comment by skimdankish** [comment]
@renegade2k 

That is correct, if you add a new item with the correct tags or  add a tag to an existing item when you say "hey google sync devices" Google Assistant sends the SYNC intent to all setup Smart Home Services (including openhab, hue, wemo, etc.)  This is the same exact function that the function performs when you first add OpenHAB in the Google Home app so it will re-assert existing items and add new ones.

This might also help you with "Smart Life" issue...

@marziman 
Unless people have problems using this command to add new devices, I think this issue should be able to be closed...

**Comment by denistbz** [comment]
I have just encountered this problem today. Italian Google Assistant is quite new so probably not yet complete. OpenHab link is just in Google App and not in Google Home. For Italians, the command for synching is "sincronizza luci". You need to say it after "ok Google" voice activation only: hitting the mike icon won't do.

**Comment by Skinah** [comment]
I have been having this issue for a long time, but until now I could unlink and relink for any new devices to be seen. After upgrading to Openhab 2.3 stable (and tried 2.4 snapshot every day for the past week) I now have a weird situation where I can only sync up to 5 devices, adding a 6th breaks the ability to both "Sync my devices" and removing and re-adding Openhab as a device fails to work since I upgraded to 2.3. It is not my items file as I can randomly choose any 5 items with tags and they work, and then add a 6th which has been tested a minute ago to work, and the 6th item will break everything. I even loaded openhabian from scratch onto my PI2 to test and even a clean fresh setup is doing this.

The cloud connector works for push notifications and exposed items, but the remote access to the dashboards is broken and comes up with:
 
504 Gateway Time-out
nginx/1.10.0 (Ubuntu) 

Everything else on my setup is working great, it is just the cloud connector and the connection to my google home mini that is playing up, any ideas?

Here is my log output...

```

2018-07-21 15:13:04.057 [DEBUG] [io.openhabcloud.internal.CloudClient] - on(): cancel

2018-07-21 15:13:04.063 [DEBUG] [io.openhabcloud.internal.CloudClient] - Received cancel for request 21675993

2018-07-21 15:13:04.072 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO disconnected

2018-07-21 15:13:04.077 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = xxxx, base URL = http://localhost:8080)

2018-07-21 15:13:04.695 [TRACE] [io.openhabcloud.internal.CloudClient] - Manager.EVENT_TRANSPORT

2018-07-21 15:13:04.701 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:06.445 [TRACE] [io.openhabcloud.internal.CloudClient] - Manager.EVENT_TRANSPORT

2018-07-21 15:13:06.450 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:06.515 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:06.903 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO connected

2018-07-21 15:13:06.910 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = xxxx, base URL = http://localhost:8080)

2018-07-21 15:13:06.945 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:31.528 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:33.056 [ERROR] [io.openhabcloud.internal.CloudClient] - Socket.IO error: {}

io.socket.engineio.client.EngineIOException: xhr post error

	at io.socket.engineio.client.Transport.onError(Transport.java:71) [193:org.openhab.io.openhabcloud:2.4.0.201807161453]

	at io.socket.engineio.client.transports.PollingXHR.access$000(PollingXHR.java:19) [193:org.openhab.io.openhabcloud:2.4.0.201807161453]

	at io.socket.engineio.client.transports.PollingXHR$4$1.run(PollingXHR.java:88) [193:org.openhab.io.openhabcloud:2.4.0.201807161453]

	at io.socket.thread.EventThread$2.run(EventThread.java:80) [193:org.openhab.io.openhabcloud:2.4.0.201807161453]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

Caused by: java.io.IOException: 400

	at io.socket.engineio.client.transports.PollingXHR$Request$1.run(PollingXHR.java:218) ~[?:?]

	... 1 more

2018-07-21 15:13:33.108 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:33.116 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO disconnected

2018-07-21 15:13:33.119 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = xxxx, base URL = http://localhost:8080)

2018-07-21 15:13:34.585 [TRACE] [io.openhabcloud.internal.CloudClient] - Manager.EVENT_TRANSPORT

2018-07-21 15:13:34.593 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:36.142 [TRACE] [io.openhabcloud.internal.CloudClient] - Manager.EVENT_TRANSPORT

2018-07-21 15:13:36.147 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:36.198 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:36.589 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO connected

2018-07-21 15:13:36.593 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = xxxx, base URL = http://localhost:8080)

2018-07-21 15:13:36.604 [DEBUG] [io.openhabcloud.internal.CloudClient] - on(): request

2018-07-21 15:13:36.608 [DEBUG] [io.openhabcloud.internal.CloudClient] - Got request 21676472

2018-07-21 15:13:36.611 [DEBUG] [io.openhabcloud.internal.CloudClient] - {"host":"myopenhab.org","user-agent":"openhab-cloud/0.0.1"}

2018-07-21 15:13:36.615 [DEBUG] [io.openhabcloud.internal.CloudClient] - Request method is GET

2018-07-21 15:13:36.619 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty set header host = myopenhab.org

2018-07-21 15:13:36.628 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty set header user-agent = openhab-cloud/0.0.1

2018-07-21 15:13:36.633 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:36.879 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty finished receiving response header

2018-07-21 15:13:36.887 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent headers to request 21676472

2018-07-21 15:13:36.892 [DEBUG] [io.openhabcloud.internal.CloudClient] - {"headers":{"Transfer-Encoding":"chunked","Server":"Jetty(9.3.21.v20170918)","Content-Type":"application/json"},"responseStatusCode":200,"responseStatusText":"OK","id":21676472}

2018-07-21 15:13:36.892 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:13:36.899 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16266

2018-07-21 15:13:36.918 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:36.922 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:36.926 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:36.929 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 118

2018-07-21 15:13:36.936 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:36.943 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16258

2018-07-21 15:13:36.947 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:36.954 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:36.958 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:36.969 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 126

2018-07-21 15:13:36.973 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:36.980 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16250

2018-07-21 15:13:36.983 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:36.991 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:36.995 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.003 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 134

2018-07-21 15:13:37.006 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.014 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16242

2018-07-21 15:13:37.019 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.026 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.031 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.039 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 142

2018-07-21 15:13:37.043 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.050 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16234

2018-07-21 15:13:37.054 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.067 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.071 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.075 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 150

2018-07-21 15:13:37.078 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.082 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16226

2018-07-21 15:13:37.086 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.090 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.094 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.098 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 158

2018-07-21 15:13:37.102 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.106 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16218

2018-07-21 15:13:37.110 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.114 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.117 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.121 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 166

2018-07-21 15:13:37.124 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.128 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16210

2018-07-21 15:13:37.131 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.134 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.139 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.142 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 174

2018-07-21 15:13:37.146 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.149 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16202

2018-07-21 15:13:37.153 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.156 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.160 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.164 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 182

2018-07-21 15:13:37.168 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.172 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16194

2018-07-21 15:13:37.176 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.180 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.183 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.187 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 190

2018-07-21 15:13:37.191 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.195 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16186

2018-07-21 15:13:37.199 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.202 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.207 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.210 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 198

2018-07-21 15:13:37.215 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.218 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16178

2018-07-21 15:13:37.223 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.226 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.231 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.234 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 206

2018-07-21 15:13:37.238 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.241 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16170

2018-07-21 15:13:37.245 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.248 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16384

2018-07-21 15:13:37.252 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.255 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 214

2018-07-21 15:13:37.258 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.758 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 16376

2018-07-21 15:13:37.763 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.766 [DEBUG] [io.openhabcloud.internal.CloudClient] - Jetty received response content of size 14528

2018-07-21 15:13:37.769 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 21676472

2018-07-21 15:13:37.776 [DEBUG] [io.openhabcloud.internal.CloudClient] - Finished responding to request 21676472

2018-07-21 15:13:38.547 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:15:01.198 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO disconnected

2018-07-21 15:15:01.204 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = xxxx, base URL = http://localhost:8080)

2018-07-21 15:15:02.005 [TRACE] [io.openhabcloud.internal.CloudClient] - Manager.EVENT_TRANSPORT

2018-07-21 15:15:02.011 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:15:03.770 [TRACE] [io.openhabcloud.internal.CloudClient] - Manager.EVENT_TRANSPORT

2018-07-21 15:15:03.777 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:15:03.844 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

2018-07-21 15:15:04.255 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO connected

2018-07-21 15:15:04.260 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = xxxx, base URL = http://localhost:8080)

2018-07-21 15:15:04.271 [TRACE] [io.openhabcloud.internal.CloudClient] - Transport.EVENT_REQUEST_HEADERS

```

**Comment by c-yco** [comment]
The documentation should be updated, that it is necessary to Say "Google sync my device" to discover new devices

**Comment by marziman** [comment]
Is this still an issue? otherwise I would close it

**Comment by swampdogmash** [comment]
All seems ok for me. Didnt realise it was only achievable with a voice command. Not sure why google doesnt provide a button in the google home app to do the same.

**Comment by marziman** [comment]
Closing this..
